# Generated by Django 5.2 on 2025-07-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepiniere',
            name='capacite',
        ),
    ]
