# Generated by Django 5.2 on 2025-07-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='nom_projet',
            field=models.CharField(blank=True, help_text='Nom du projet', max_length=200),
        ),
    ]
