# Generated by Django 5.2 on 2025-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='certification_bio',
            field=models.BooleanField(default=False, help_text='Certification biologique'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='certification_hve',
            field=models.BooleanField(default=False, help_text='Certification Haute Valeur Environnementale'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='cout_production',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût de production en euros/ha', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='date_recolte_prevue',
            field=models.DateField(blank=True, help_text='Date de récolte prévue', null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='date_semis',
            field=models.DateField(blank=True, help_text='Date de semis', null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='irrigation',
            field=models.BooleanField(default=False, help_text='Parcelle irriguée'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes et observations', null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='rendement_prevue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendement prévu en tonnes/ha', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie en hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_irrigation',
            field=models.CharField(blank=True, help_text="Type d'irrigation", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_sol',
            field=models.CharField(blank=True, help_text='Type de sol', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='variete',
            field=models.CharField(blank=True, help_text='Variété de la culture', max_length=100, null=True),
        ),
    ]
