# Generated by Django 5.2 on 2025-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_remove_pepiniere_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepiniere',
            name='nom_projet',
            field=models.CharField(blank=True, help_text='Nom du projet', max_length=200),
        ),
    ]
