# Generated by Django 5.2 on 2025-07-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_parcelle_certification_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du membre', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='geojson',
            field=models.JSONField(help_text='Données GeoJSON converties depuis les fichiers uploadés'),
        ),
        migrations.CreateModel(
            name='ParcelleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image de la parcelle', upload_to='parcelles/')),
                ('titre', models.CharField(blank=True, help_text="Titre de l'image", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text="Description de l'image", null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parcelles.parcelle')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
