# Generated by Django 5.2 on 2025-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0004_siege'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abreviation',
            field=models.CharField(blank=True, help_text='Abréviation du membre', max_length=20),
        ),
    ]
