# Generated by Django 5.2 on 2025-07-12 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0005_user_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de la personne référente', max_length=254),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='nom_personne_referente',
            field=models.CharField(blank=True, help_text='Nom de la personne référente', max_length=100),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='poste',
            field=models.CharField(blank=True, help_text='Poste de la personne référente', max_length=100),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='telephone',
            field=models.CharField(blank=True, help_text='Téléphone de la personne référente', max_length=20),
        ),
        migrations.AddField(
            model_name='siege',
            name='categorie',
            field=models.CharField(choices=[('national', 'National'), ('régional', 'Régional'), ('bureau', 'Bureau')], default='bureau', help_text='Catégorie du siège', max_length=20),
        ),
        migrations.AddField(
            model_name='siege',
            name='email',
            field=models.EmailField(blank=True, help_text='Email du point de contact', max_length=254),
        ),
        migrations.AddField(
            model_name='siege',
            name='horaire_apres_midi',
            field=models.CharField(blank=True, help_text="Horaires de l'après-midi", max_length=100),
        ),
        migrations.AddField(
            model_name='siege',
            name='horaire_matin',
            field=models.CharField(blank=True, help_text='Horaires du matin', max_length=100),
        ),
        migrations.AddField(
            model_name='siege',
            name='nom_point_contact',
            field=models.CharField(blank=True, help_text='Nom du point de contact', max_length=100),
        ),
        migrations.AddField(
            model_name='siege',
            name='poste',
            field=models.CharField(blank=True, help_text='Poste du point de contact', max_length=100),
        ),
        migrations.AddField(
            model_name='siege',
            name='telephone',
            field=models.CharField(blank=True, help_text='Téléphone du point de contact', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_institution',
            field=models.CharField(blank=True, help_text="Nom de l'institution", max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_projet',
            field=models.CharField(blank=True, help_text='Nom du projet', max_length=200),
        ),
        migrations.CreateModel(
            name='Pepiniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('national', 'National'), ('régional', 'Régional'), ('bureau', 'Bureau')], default='bureau', help_text='Catégorie de la pépinière', max_length=20)),
                ('nom_point_contact', models.CharField(blank=True, help_text='Nom du point de contact', max_length=100)),
                ('poste', models.CharField(blank=True, help_text='Poste du point de contact', max_length=100)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone du point de contact', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email du point de contact', max_length=254)),
                ('horaire_matin', models.CharField(blank=True, help_text='Horaires du matin', max_length=100)),
                ('horaire_apres_midi', models.CharField(blank=True, help_text="Horaires de l'après-midi", max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_gestionnaire', models.CharField(blank=True, help_text='Nom du gestionnaire', max_length=100)),
                ('poste_gestionnaire', models.CharField(blank=True, help_text='Poste du gestionnaire', max_length=100)),
                ('telephone_gestionnaire', models.CharField(blank=True, help_text='Téléphone du gestionnaire', max_length=20)),
                ('email_gestionnaire', models.EmailField(blank=True, help_text='Email du gestionnaire', max_length=254)),
                ('especes_produites', models.TextField(blank=True, help_text='Espèces produites')),
                ('capacite', models.DecimalField(blank=True, decimal_places=2, help_text='Capacité de production', max_digits=10, null=True)),
                ('quantite_production_generale', models.TextField(blank=True, help_text='Quantité de production générale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepinieres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PepiniereImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo de la pépinière', upload_to='pepinieres/')),
                ('titre', models.CharField(blank=True, help_text="Titre de l'image", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text="Description de l'image", null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parcelles.pepiniere')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo du bâtiment', upload_to='sieges/')),
                ('titre', models.CharField(blank=True, help_text="Titre de l'image", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text="Description de l'image", null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_batiment', to='parcelles.siege')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
