# Generated by Django 5.2 on 2025-07-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0006_parcelle_email_parcelle_nom_personne_referente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepiniere',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='horaire_apres_midi',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='horaire_matin',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='nom_point_contact',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='pepiniere',
            name='telephone',
        ),
    ]
