# Generated by Django 5.2 on 2025-07-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_remove_pepiniere_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepiniere',
            name='categorie',
        ),
    ]
