# Generated by Django 5.2 on 2025-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0008_remove_pepiniere_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siege',
            name='categorie',
            field=models.CharField(choices=[('social', 'Siège social'), ('regional', 'Siège régional'), ('technique', 'Siège technique'), ('provisoire', 'Siège provisoire')], default='bureau', help_text='Catégorie du siège', max_length=20),
        ),
    ]
